---
- hosts: all
  gather_facts: True
  become: true
  tasks:
  - name: Enable EPEL Repository on Oracle Linux 8
    dnf:
      name: epel-release
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '8'
